<a href="https://colab.research.google.com/github/rukminit28/Intrenship/blob/master/numpy%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [2]:
a.transpose()                                #it converts rows into col

array([[1., 3.],
       [2., 4.]])

In [3]:
np.linalg.inv(a)                              #a inverse is=adj(a)/det(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
u=np.eye(3)                              #unit matrix 3*3 "eye" represent "I" iedentity matrix
u

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
print(j)

[[ 0. -1.]
 [ 1.  0.]]


In [11]:
j@j                                          #matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [12]:
np.trace(u)

3.0

In [13]:
y = np.array([[5.], [7.]])                      #slove 1x+2Y=5 and 3X+4Y=7 by using linear eqn
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [17]:
from array import* 
my_array=array('i',[1,2,3,4,5,6,7])                 #create a simple array and print it
for i in my_array:
  print(i)

1
2
3
4
5
6
7


In [18]:
my_array[4]                              #indivisual ele can be accesed through indexes

5

In [21]:
my_array.append(8)
my_array                                                  #here 8 will be appended(added) at the end of my_array

array('i', [1, 2, 3, 4, 5, 6, 7, 4, 8])

In [22]:
my_array.insert(0,0)
my_array                                                    #here insert means at particular index the value will be added


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 4, 8])

In [41]:
my_array.insert(9,2)
my_array

array('i', [0, 3, 4, 5, 6, 7, 4, 11, 9, 2, -1, 9, 8, 2, 3])

In [28]:
my_extnd_array=array('i', [2,3])
my_array.extend(my_extnd_array)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 4, 11, 10, 9, 8, 2, 3])

In [29]:
r=[4,5,6]
my_array.fromlist(r)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 4, 11, 10, 9, 8, 2, 3, 4, 5, 6])

In [34]:
my_array.remove(1)
my_array

array('i', [0, 3, 4, 5, 6, 7, 4, 11, 9, 8, 2, 3, 4, 5, 6])

In [53]:
my_array.pop()                   #here last element will be popped
my_array

array('i', [0, 3, 4, 5, 6, 7, 4, 9, 2, -1])

In [45]:
my_array.index(11)                      #here 11th index value will print

7

In [48]:
my_array.buffer_info()

(140328550257728, 15)

In [55]:
my_array.count(4)                    #here 4 will occurs 2 times so count is 2

2

In [56]:
my_array.count(3)

1

In [63]:
my_char_array=array('b',[ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

array('b', [103, 101, 101, 107])

In [66]:
c=my_array.tolist()
c

[0, 3, 4, 5, 6, 7, 4, 9, 2, -1]

In [67]:
my_char_array.fromstring("stuff")
my_char_array

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])