<a href="https://colab.research.google.com/github/rukminit28/Intrenship/blob/master/numpy%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [6]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
b=np.arange(3)
print(b)

[0 1 2]


In [12]:
np.exp(b)


array([1.        , 2.71828183, 7.3890561 ])

In [13]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [0]:
C=np.array([2,-1.,4.])

In [18]:
np.add(b,C)

array([2., 0., 6.])

In [20]:
np.all(C)

True

In [21]:
np.sort(C)

array([-1.,  2.,  4.])

In [24]:
np.any(C)

True

In [26]:
np.vectorize(C)

In [28]:
a=np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [29]:
a[3]


27

In [0]:
a[:6:2]=-1000

In [38]:
print(a)

[-1000     1 -1000]


In [40]:
a[::-1]          #reverse of a
print(a)

[-1000     1 -1000]


In [42]:
s="hello world"
print(s)

hello world


In [46]:
s[-2:]

'ld'

In [49]:
r=np.arange(24).reshape(2,3,4)    #first matrix 0th matrix
print(r)                          #second matrix 1th matrix shown in below resultant matrix


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [60]:
for  i in range(2):
  r[:,:,i]
  print(r)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [65]:
r[-1,2]

array([20, 21, 22, 23])

In [82]:
r[0,2,0]

8

In [84]:
r[1,0,2]     # here in 1th matrix 0th row ,2nd coloumn will print 

14

In [94]:
r[:,::1,::2]                   # : means from both matrix ,::means in 0th matrix (rows) it print 1 step by 1 step
                               #::2 (coloumn) 0 and 2th coloumn will print

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [95]:
r[:,:2,:4]                                   # here :means in two matrix 
                                             #:2 2rows (1st and 2nd row) will print
                                             #:4 4rows will print without jumping ele

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [96]:
for row in r:
  print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [98]:
for element in r.flat:
  print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [100]:
for coloumn in r:
  print(coloumn)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [101]:
r = np.floor(10*np.random.random((3,4)))
print(r)


[[8. 4. 4. 4.]
 [5. 7. 4. 0.]
 [7. 5. 2. 9.]]


In [102]:
r.ravel()                              #it returns flatened array


array([8., 4., 4., 4., 5., 7., 4., 0., 7., 5., 2., 9.])

In [106]:
r.reshape(6,2)

array([[8., 4.],
       [4., 4.],
       [5., 7.],
       [4., 0.],
       [7., 5.],
       [2., 9.]])

In [107]:
r.T                                             #it will convert rows into colounm and col int rows

array([[8., 5., 7.],
       [4., 7., 5.],
       [4., 4., 2.],
       [4., 0., 9.]])