<a href="https://colab.research.google.com/github/rukminit28/Intrenship/blob/master/python%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a.shape

(3, 5)

In [4]:
np.__version__

'1.16.4'

In [5]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [13]:
c=np.array([(2,3,4),(5,6,7)])
print(c)

[[2 3 4]
 [5 6 7]]


In [0]:
d=np.

In [19]:
import numpy as np
a=np.arange(30).reshape(2,5,3)
print(a)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [20]:
a.ndim

3

In [21]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [22]:
b.dtype

dtype('float64')

In [44]:
c = np.array( [ [1,6+5j], [5,3+4j] ], dtype=complex )
print(c)

[[1.+0.j 6.+5.j]
 [5.+0.j 3.+4.j]]


In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
d=np.array([(1.0,2.0,3.0),(4.0,5.0,6.0),(7.0,8.0,9.0)])
print(d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [27]:
d.dtype

dtype('float64')

In [30]:
np.empty((2,3))

array([[9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323]])

In [40]:
np.ones( (2,3,3), dtype=np.float16 )  

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float16)

In [45]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [48]:
from numpy import pi
np.linspace( 0, 2, 6 ) 

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [51]:
x=np.linspace(0,2*pi,100)
f=np.sin(x)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [53]:
p=np.arange(3)
print(p)

[0 1 2]


In [55]:
t=np.arange(12).reshape(4,3)
print(t)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
r=np.arange(24).reshape(2,3,4)
print(r)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [59]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(b)



[0 1 2 3]


In [60]:
c=a-b
print(c)

[20 29 38 47]


In [61]:
c**2

array([ 400,  841, 1444, 2209])

In [66]:
a<35


array([ True,  True, False, False])

In [67]:
A = np.array( [[1,1],
         [0,1]] )
B= np.array([[0,2],[3,4]])
A*B

array([[0, 2],
       [0, 4]])